### ISSUE TITLE
About flyweight pattern

### ISSUE THREAD

**Issue by dshemin** [AlexanderGrom/go-patterns#16]
Hi! Thanks for the collection of design patterns in Go!

Unfortunately, you have an issue with the "flyweight" pattern here. Please take a look at this example in playground https://play.golang.org/p/fZM6N97Y9yX

In case if something will happen with golang playground I passed code here as well:

```golang
package main

import (
	"fmt"
)

type Flyweighter interface {
	GetName() string
	SetName(name string)
}

type FlyweightFactory struct {
	pool map[int]Flyweighter
}

func (f *FlyweightFactory) GetFlyweight(state int) Flyweighter {
	if f.pool == nil {
		f.pool = make(map[int]Flyweighter)
	}
	if _, ok := f.pool[state]; !ok {
		f.pool[state] = &ConcreteFlyweight{state: state}
	}
	return f.pool[state]
}

type ConcreteFlyweight struct {
	state int
	name  string
}

func (f *ConcreteFlyweight) GetName() string {
	return "My name: " + f.name
}

func (f *ConcreteFlyweight) SetName(name string) {
	f.name = name
}

func main() {
	factory := FlyweightFactory{}

	instance1 := factory.GetFlyweight(1)
	instance2 := factory.GetFlyweight(1)
	
	fmt.Println(instance1.GetName())
	fmt.Println(instance2.GetName())

	instance1.SetName("instance1")
	instance2.SetName("instance2")
	
	fmt.Println(instance1.GetName())
	fmt.Println(instance2.GetName())
}
```

I don't have much experience with that pattern but I believe we have the next options here:

1. Object shouldn't provide setters;
2. We should use something like COW here and each setter should create a new instance instead of mutating the current one.

**Comment by AlexanderGrom** [comment]
Hi! You are right, I chose a bad example.
The "flyweight" can have mutable or immutable state, but not in this example.

I can provide a link to the wiki:
https://en.wikipedia.org/wiki/Flyweight_pattern#Mutable_or_immutable_extrinsic_state

I probably need to fix the example.
