### ISSUE TITLE
Specifications Pattern

### ISSUE THREAD

**Issue by spaiz** [AlexanderGrom/go-patterns#5]
Hi. I would like to see an attempt to implement Specifications Pattern.

https://www.martinfowler.com/apsupp/spec.pdf

Less formal:
https://en.wikipedia.org/wiki/Specification_pattern

Currently in my project I implemented it using interfaces, but it looks ugly without generics and real inheritance. I have lot of copy past the same code :(

Wanna try?

**Comment by AlexanderGrom** [comment]
Hi! Look at this.
https://gist.github.com/AlexanderGrom/586c9aa1f0af7b325ecfcfdc1da360ff

**Comment by spaiz** [comment]
Looks great! Thanks!
